M48
; DRILL file {KiCad 7.0.7} date Sat Oct 14 23:11:56 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-14T23:11:56-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X112.395Y-106.426
X112.395Y-135.636
X149.276Y-69.85
X168.275Y-122.555
T0
M30
