M48
; DRILL file {KiCad 7.0.2} date Wed Oct 18 14:35:03 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-18T14:35:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X112.395Y-106.426
X112.395Y-135.636
X149.276Y-69.85
X168.275Y-122.555
T0
M30
